dist: trusty
language: node_js
node_js:
  - "8"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python3.6
  - sudo apt-get install -qq chromium-browser coreutils g++ git python-dev python-virtualenv xvfb realpath
install:
  - pip3 install -r requirements.txt
script:
  - yarn run test
